spring:
    application:
        name: bizobj-llm-t001-testsuites
    config.import:
        - classpath:/config-units/testsuites.yml

# Disable built-in OpenAI Model
spring.ai.openai.base-url: "https://not-existed.local/"
spring.ai.openai.api-key: "******"
